apiVersion: v1
kind: Service
metadata:
    name: "aksdemo-6fba"
    labels:
        app: "aksdemo-6fba"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksdemo-6fba"