apiVersion: v1
kind: Service
metadata:
    name: "aksdemo-3253"
    labels:
        app: "aksdemo-3253"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksdemo-3253"